---
- name: Install and Configure Fail2Ban for SSH Protection on Ubuntu
  hosts: all
  become: true
  vars:
    # SSH jail configuration
    ssh_bantime: "1h"
    ssh_findtime: "10m"
    ssh_maxretry: 3

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Fail2Ban
      ansible.builtin.apt:
        name: fail2ban
        state: present

    - name: Create jail.local configuration for SSH protection
      ansible.builtin.copy:
        content: |
          [sshd]
          enabled = true
          port = ssh
          filter = sshd
          logpath = /var/log/auth.log
          maxretry = {{ ssh_maxretry }}
          bantime = {{ ssh_bantime }}
          findtime = {{ ssh_findtime }}
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: "0644" # Setup file perms
        backup: true
      notify: restart fail2ban

    - name: Start and enable Fail2Ban service
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        enabled: true

    - name: Check SSH jail status
      ansible.builtin.command: fail2ban-client status sshd
      register: ssh_jail_status
      changed_when: false
      failed_when: false

    - name: Display SSH jail status
      ansible.builtin.debug:
        msg: "{{ ssh_jail_status.stdout_lines }}"
      when: ssh_jail_status.rc == 0

    - name: Show default Fail2Ban log location
      ansible.builtin.debug:
        msg: "Fail2Ban logs are available at: /var/log/fail2ban.log"

  handlers:
    - name: Restart Fail2Ban
      ansible.builtin.systemd:
        name: fail2ban
        state: restarted
